# build environment
FROM node:alpine as build
WORKDIR /app
ADD  package*.json ./
RUN npm install
COPY . .
# production environment
RUN npm run build 
FROM nginx
COPY --from=build /app/build /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]