version: '3.7'
services:
    grafana:
        image: grafana/grafana
        restart: always
        container_name: grafana
        ports:
            - '4000:3000'
        volumes: 
            - ./grafana-data:/var/lib/grafana

    db:
        image: postgres
        restart: always
        container_name: db            
        ports: 
            - '5433:5432'
        environment: 
            POSTGRES_DB: 'teste'
            POSTGRES_USER: 'teste'
            POSTGRES_PASSWORD: 'teste'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    app:
        container_name: frontend
        build: 
            "./frontend"
        volumes: 
            - './frontend:/usr/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development            
        stdin_open: true
        # depends_on: 
        #     - db
        
    app-prod:
        container_name: app-prod
        build:
            context: frontend/
            dockerfile: Dockerfile-prod
        ports:
            - '8080:80'
    
    # server:
    #     build: 
    #         "./server"
    #     container_name: server
    #     restart: always
    #     volumes: 
    #         - ./server:/usr/server


        
            